### PR TITLE
try again, sigh

### PR DESCRIPTION
**Pull request by vielmetti**
try2 for hugo2 plugin2

### CODE REVIEW

**Comment by vielmetti** [comment]
not working, close. we'll zero out drone, and start afresh.

**Comment by immanuelfodor** [comment]
Hi, I've seen your struggle at https://cloud.drone.io/vielmetti/commonplace and I get the same no layout found error all the time with the hugo plugin. Could you solve it somehow in the end? Or went for Travis CI right away? When I build locally, everything is fine, but in the CI, the error appears. Is it the problem that the theme is added as a submodule?

**Comment by vielmetti** [comment]
@immanuelfodor - 

I admit that I don't completely understand all of the interconnections among those modules, and for the most part the Hugo setup I have under Netlify "just works". I'll revisit this again when I have more time or another motivation for it. Good luck with your configuration!

**Comment by immanuelfodor** [comment]
Apparently, the Drone docs is missing an important step at the recursive usage: https://docs.drone.io/pipeline/docker/syntax/cloning/

```diff
  steps:
  - name: submodules
    image: alpine/git
    commands:
+   - git submodule init
    - git submodule update --recursive --remote
```

It took me some time to figure it out, I hope it helps :)

**Pull request closed without merging**
